// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN222.MilkTeaShop.Repository.Models;

public partial class Order
{
    public int Id { get; set; }

    public decimal TotalPrice { get; set; }

    public string Status { get; set; } = "pending";
    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public void UpdateStatus(string newStatus)
    {
        if (newStatus == "pending" || newStatus == "completed" || newStatus == "cancelled")
        {
            Status = newStatus;
            UpdatedAt = DateTime.Now;
        }
    }
}